### ISSUE TITLE
`tomllib` is considered as third-party lib in py3.11 but it is built-in now

### ISSUE THREAD

**Issue by NickVeld** [PyCQA/isort#2007]
https://docs.python.org/3/library/tomllib.html

It can be a part of an "epic" called "Support for python3.11" #1996 

Behavior before:
```
@@ -1,8 +1,10 @@
-import tomllib
from pathlib import Path
from typing import Generator
 
+import tomllib
...
```

Behavior after:
The message that everything is OK

Version: 5.10.1

**Comment by NickVeld** [comment]
### Workarounds:

#### pyproject.toml
```
[tool.isort]
extra_standard_library = ['tomllib']
```

#### setup.cfg
```
[isort]
extra_standard_library = tomllib
```

#### [Action comments](https://pycqa.github.io/isort/docs/configuration/action_comments.html) (not recommended)
```
import tomllib  # isort: skip
```

**Comment by NickVeld** [comment]
Maybe built-in `tomllib` support can be enabled by `py_version=311` when it is added #2008

**Comment by andersk** [comment]
This seems to have been fixed by #2024 (not released yet) with `py_version=311`.

**Comment by staticdev** [comment]
@andersk released, 5.11.0.

**Comment by bszonye** [comment]
This is still broken for me in isort 5.11.2 (on Ubuntu 22.10). I suspect that's because they're distributing Python 3.11.0rc, which has the new feature, but that version is not technically `>=3.11`. I ran into that just the other day with another tool. I suspect that affects anybody running a pre-release version of Python 3.11.

**Comment by andersk** [comment]
No, it’s because #2024 had [bugs](https://github.com/PyCQA/isort/pull/2024#pullrequestreview-1218455046).
