### ISSUE TITLE
`--sort-reexports` is broken

### ISSUE THREAD

**Issue by monosans** [PyCQA/isort#2037]
I decided to put two bugs in the same issue because I think `sort-reexports` is highly unstable and both bugs should be dealt with together.

### Bug 1

```python
__all__ = ('foo', 'bar')
```

Running `isort --sort-reexports` on this code creates a new `__all__` instead of replacing the existing one.

```python
__all__ = ('foo', 'bar')
__all__ = ('bar', 'foo')
```

### Bug 2

If you make `__all__` a tuple without parentheses, then isort will just crash.

```python
__all__ = 'bar', 'foo'
```

```python
ERROR: Unrecoverable exception thrown when parsing main.py! This should NEVER happen.
If encountered, please open an issue: https://github.com/PyCQA/isort/issues/new
Traceback (most recent call last):
  File "/home/user/.local/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/isort/main.py", line 1225, in main
    for sort_attempt in attempt_iterator:
  File "/home/user/.local/lib/python3.10/site-packages/isort/main.py", line 1209, in <genexpr>
    sort_imports(  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/isort/main.py", line 93, in sort_imports
    incorrectly_sorted = not api.sort_file(
  File "/home/user/.local/lib/python3.10/site-packages/isort/api.py", line 429, in sort_file
    changed = sort_stream(
  File "/home/user/.local/lib/python3.10/site-packages/isort/api.py", line 210, in sort_stream
    changed = core.process(
  File "/home/user/.local/lib/python3.10/site-packages/isort/core.py", line 236, in process
    code_sorting = LITERAL_TYPE_MAPPING[stripped_line.split(" = ")[1][0]]
KeyError: "'"
```

### Technical info

OS: Arch Linux
Python 3.10.8
isort 5.11.1

**Comment by staticdev** [comment]
Indeed I reproduced the error, this option was introduced by [parafoxia](https://github.com/parafoxia), maybe you have an idea what is wrong?

**Comment by parafoxia** [comment]
I actually did notice this, though am not 100% sure why it's happening. It wasn't happening when I developed it, but that was over a year ago so anything could've happened in the meantime. I'll have another look tomorrow probably.

**Comment by parafoxia** [comment]
So I decided to look at it tonight, and both errors have been fixed @monosans @staticdev. I'm just gonna run through and double check stuff then create a PR.

**Comment by kevalmorabia97** [comment]
Seems like after the PR is merged, this still does not work as expected and breaks `__all__` if `--sort-reexports` flag is used

**Comment by parafoxia** [comment]
It's working fine for me. What version of isort are you using?

**Comment by mrcljx** [comment]
@parafxia Minimal example using 5.12.0:

```python
from x import (
    y,
)


def z():
    return y()


__all__ = [
    "z",
    "y",
]
```

emits as

```python
from x import y


def z():
   __all__ = ['y', 'z']
 = [
```

Seems to be triggered by the multi-line `from x import` (changing it to `from x import y` doesn't cause the issue).

**Comment by parafoxia** [comment]
Ah, I think I see what might be happening here. I'll try and have a look at it some point over the next few days.
